spring.application.name=client
logging.pattern.console=%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %5p [traceId=%X{traceId:-},spanId=%X{spanId:-}] %-40.40logger{39} : %m%n

logging.level.com.registration.client: TRACE